# @package _group_

common:
  fp16: false
  log_format: json
  log_interval: 200
  all_gather_list_size: 70000
  tensorboard_logdir: tb
  min_loss_scale: 1e-6

checkpoint:
  save_interval: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: mAP
  maximize_best_checkpoint_metric: true

task:
  _name: audioset_classification
  data: ???

dataset:
  num_workers: 1
  max_tokens: 2560000
  skip_invalid_size_inputs_valid_test: true
  valid_subset: test
  validate_interval: 5

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 1

criterion:
  _name: model
  can_sum: false
  log_keys:
    - _predictions
    - _targets

optimization:
  max_update: 30000
  lr: [0.00006] # scratch 53-5

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: cosine
  warmup_updates: 5000

model:
  _name: passt
  s_patchout_f: 8
  s_patchout_t: 8

